### ISSUE TITLE
開発環境に関して(キャッシュ周り)

### ISSUE THREAD

**Issue by yupix** [TeamOrangeServer/misskey#25]
正直現状、変更内容をbuildしブラウザを開いても変更が反映されないなど、現状を維持したまま開発するのは私とsousuke共に精神的に疲れるので、Dockerの中にDesktopを構築して、以下の方法で接続するのがいいかも...?

- XRDP
- VNC
- X Server

**Comment by sousuke0422** [comment]
問題が軽減されたはずですがどうですか？
問題なければ閉じます

**Comment by sousuke0422** [comment]
問題なさそうなはずだから閉じるわ
