### ISSUE TITLE
既存インスタンスを引き継げない

### ISSUE THREAD

**Issue by sousuke0422** [TeamOrangeServer/misskey#26]
## 💡 Summary

db周りのエラーで正常に動作しない

## 🙂 Expected Behavior

`migrate`タスク実行後に正常にログインでき、新機能をつかえる。

## ☹️ Actual Behavior

`migrate`タスク実行後に起動しても、エラーが出て存在するアカウントにもログイン不可

## 📝 Steps to Reproduce

1. yarn build && yarn migrateandstart

## 📌 Environment

windows10上で動作するredis 4とpostgres 11

**Comment by sousuke0422** [comment]
新規で立てた場合はどうなるの？

**Comment by sousuke0422** [comment]
エラーよく読んだらisCatが破壊されてそう

**Comment by yupix** [comment]
isCatが破壊されてるってのはどういった形で現れてる?

**Comment by yupix** [comment]
既存のデータベースにはisLadyテーブルが存在しないため恐らく発生していると思います

**Comment by sousuke0422** [comment]
isCatの見た目をしたisLadyでしたわ

**Comment by yupix** [comment]
[55c0f39](https://github.com/TeamOrangeServer/misskey/commit/55c0f39caad674b65149edead4726c83fd87f341)と[61a2888](https://github.com/TeamOrangeServer/misskey/commit/61a2888dac78fd64cb3e6e27b87d165648b6d5ee)で一応対応作業自体は行いましたが動作確認は取れていません。

**Comment by sousuke0422** [comment]
v4.0.0で一応解決
