### ISSUE TITLE
トークの読み込みが終わらない

### ISSUE THREAD

**Issue by yupix** [TeamOrangeServer/misskey#61]
## 💡 Summary

v1~v2あたりでトークが読み込みのまま終わらなくなってる

## 📝 Steps to Reproduce

1. v2~v3にアップデートする

## 📌 Environment

不明

**Comment by sousuke0422** [comment]
まじで謎😇

**Comment by sousuke0422** [comment]
rc.2は動いた

**Comment by sousuke0422** [comment]
私はrc.2とrc.3の間にメッセージ周りいじってないぞ？？？

**Comment by sousuke0422** [comment]
a46e99596bc932580d5ab00fc9b640b566477a7a をRevertしたら治ったった
テーマの状況見てブラーかけてる場所が悪さしてそう

**Comment by yupix** [comment]
ふーむ、別の方法考えるか

**Comment by yupix** [comment]
一応、トークが使えないのは不便なので、次のコミットで機能を一時的に削除します。いい解決策が思いついたら再実装します、デフォルトで色々とおかしい部分はある程度直しているはずなので、最低限見た目は問題ないはずです
