### ISSUE TITLE
モバイルで引用Renoteできない

### ISSUE THREAD

**Issue by sousuke0422** [TeamOrangeServer/misskey#64]
## 💡 Summary

モバイルで引用Renoteできない

## 📝 Steps to Reproduce

1. モバイルで適当なNoteをRNしようとする

## 📌 Environment

プレビューつけたあたりから？

**Comment by sousuke0422** [comment]
これが終わったらrcはおしまい！

**Comment by yupix** [comment]
rcの次何?

**Comment by sousuke0422** [comment]
5.0.0

**Comment by sousuke0422** [comment]
現在は5.0.0-rc.17

**Comment by sousuke0422** [comment]
![326152aa392e9f95c292383aa188d14e 1](https://user-images.githubusercontent.com/33174568/104036652-01a13680-5217-11eb-9e02-ad283722b047.png)

**Comment by yupix** [comment]
どうやら、textareaの中身がかなり空っぽに近い状態になってたっぽいので修正した

**Comment by yupix** [comment]
リリースお願い
