### ISSUE TITLE
ci死んでるのとmigrate, devが動かない

### ISSUE THREAD

**Issue by yupix** [TeamOrangeServer/misskey#691]
## 💡 Summary

yarn migrateとyarn devが動かない
あとciがこけてる。私のエラー側だとlogger.jsが関係ありそうだけどよくわかんない

## 🙂 Expected Behavior

普通に動く

## ☹️ Actual Behavior

エラーで落ちる

## 📝 Steps to Reproduce

1. 最新のayuskeyをcloneする
2. ビルドする
3. migrate またはdevを実行する

**Comment by sousuke0422** [comment]
仕様でした
修正済み
