### ISSUE TITLE
リアクションの表示がおかしい

### ISSUE THREAD

**Issue by sousuke0422** [TeamOrangeServer/misskey#73]
## 💡 Summary

https://kr.akirin.xyz/notes/8177e192b1e9feed4d0f0787
現状仕様

## 📝 Steps to Reproduce

1.
2.
3.

**Comment by yupix** [comment]
このバグの再現方法は?

**Comment by sousuke0422** [comment]
5.6.0で標準のリアクションをつける

**Comment by sousuke0422** [comment]
ローカルカスタム絵文字のやつと似たような原因だと思うわ
