### ISSUE TITLE
絵文字の背景が透明なのは違和感がある

### ISSUE THREAD

**Issue by yupix** [TeamOrangeServer/misskey#74]
## 💡 Summary

絵文字の背景が透明なのはなんか微妙だけど多分これは少し前に言っていたリモート絵文字を押せなくする際に`canToggle`を付けてるやつにだけcssがついてるからで使えない奴にもなんかいい感じに色付けようと思ってるけど問題ないならそういってくれたらこっちでやる(案はないので期待せずに

## 🙂 Expected Behavior
![image](https://user-images.githubusercontent.com/50538210/109414246-4b2b2800-79f5-11eb-945d-50ecd8623119.png)

## ☹️ Actual Behavior
![image](https://user-images.githubusercontent.com/50538210/109414187-ebcd1800-79f4-11eb-9a86-67263eb247ce.png)

## 📝 Steps to Reproduce
1. ver5.7.0のayuskeyでリアクションを付ける、つけられたらなる

## 📌 Environment

version: 5.7.0
Instance with error: https://ne.akarinext.org

**Comment by sousuke0422** [comment]
仕様だわ
押せないリアクションが押せるのと同じだと区別しづらいから
なんかいい案あるの？

**Comment by yupix** [comment]
文章呼んで(?)

> 絵文字の背景が透明なのはなんか微妙だけど多分これは少し前に言っていたリモート絵文字を押せなくする際に`canToggle`を付けてるやつにだけcssがついてるからで使えない奴にもなんかいい感じに色付けようと思ってるけど問題ないならそういってくれたらこっちでやる(案はないので期待せずに

**Comment by sousuke0422** [comment]
えー
背景色ある方が違和感あるからやるなら後から設定で付けられるようにするくらい

**Comment by yupix** [comment]
まあ、案考えとくわ
